<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * Seeds projects with specific IDs from production database.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Truncate table
        DB::table('projects')->truncate();

        // Insert data with specific IDs from production
        $projects = [
            [
                'id' => 43,
                'user_id' => 27,
                'code_projet' => 'DUTA-UTA-0043',
                'nom_projet' => 'SGSN',
                'type_projet' => 'Externe',
                'nature_projet' => 'B2B',
                'axe_strategique' => 'Déploiement & Exploitation',
                'filiale_executant' => 'Univers Télécom Afrique',
                'filiale_contractant' => 'Univers Télécom Afrique',
                'direction_executant' => 'DIRECTION UTA',
                'direction_contractant' => 'DIRECTION UTA',
                'owner_executant' => 'Awa Gueye SALL',
                'owner_contractant' => 'Awa Gueye SALL',
                'date_demarrage' => '2025-09-26',
                'date_fin' => '2025-12-26',
                'statut_initial' => 'Planifié',
                'budget_initial' => null,
                'objectif_projet' => 'Il s\'agit d\'un projet de modernisation et d\'externalisation de l\'infrastructure de sécurité de la SGSN. Il faudra fédérer toutes les solutions de séreté, assurer un fonctionnement H24/J7 avec des SLA stricts et proposer une externalisation totale ou modulaire (infrastructure, stockage vidéo, PCS). Les critéres de sélection privilégient la compatibilité avec l\'existant, la qualité technique et humaine et le respect des normes et réglementations.',
                'prochaine_etape' => '',
                'ms_group_id' => '6efc573b-fd7d-4fd9-b3e1-067728896629',
                'ms_plan_id' => '4FKGLYsT00qeNtG9oaVkC2UAHrTV',
                'ms_bucket_id' => 'ZnDOrHmnLkKjzv1YZGPX9WUALodK',
                'sf_opportunity_id' => null,
                'sf_opportunity_name' => null,
                'sf_opportunity_stage' => null,
                'sf_opportunity_amount' => null,
                'created_at' => '2025-09-25 21:59:14',
                'updated_at' => '2025-09-25 21:59:14',
            ],
            [
                'id' => 44,
                'user_id' => 27,
                'code_projet' => 'DUTA-UTA-0044',
                'nom_projet' => 'SGSN',
                'type_projet' => 'Externe',
                'nature_projet' => 'B2B',
                'axe_strategique' => 'Déploiement & Exploitation',
                'filiale_executant' => 'Univers Télécom Afrique',
                'filiale_contractant' => 'Univers Télécom Afrique',
                'direction_executant' => 'DIRECTION UTA',
                'direction_contractant' => 'DIRECTION UTA',
                'owner_executant' => 'Awa Gueye SALL',
                'owner_contractant' => 'Awa Gueye SALL',
                'date_demarrage' => '2025-09-26',
                'date_fin' => '2025-12-26',
                'statut_initial' => 'Planifié',
                'budget_initial' => null,
                'objectif_projet' => 'Il s\'agit d\'un projet de modernisation et d\'externalisation de l\'infrastructure de sécurité de la SGSN. Il faudra fédérer toutes les solutions de séreté, assurer un fonctionnement H24/J7 avec des SLA stricts et proposer une externalisation totale ou modulaire (infrastructure, stockage vidéo, PCS). Les critéres de sélection privilégient la compatibilité avec l\'existant, la qualité technique et humaine et le respect des normes et réglementations.',
                'prochaine_etape' => '',
                'ms_group_id' => '78e3401b-ff94-41b1-9a89-c818ae92853f',
                'ms_plan_id' => 'Dbc0kKAgLECMDodGy11UdmUAAA3A',
                'ms_bucket_id' => 'eyhC_2i8GECNlKOOycqHbGUAEwJn',
                'sf_opportunity_id' => null,
                'sf_opportunity_name' => null,
                'sf_opportunity_stage' => null,
                'sf_opportunity_amount' => null,
                'created_at' => '2025-09-25 21:59:18',
                'updated_at' => '2025-09-25 21:59:18',
            ],
            [
                'id' => 45,
                'user_id' => 27,
                'code_projet' => 'INNOVCP-CP-0045',
                'nom_projet' => 'E-TERAL',
                'type_projet' => 'Interne',
                'nature_projet' => 'B2C',
                'axe_strategique' => 'Produits & Services',
                'filiale_executant' => 'Cabinet Pencco',
                'filiale_contractant' => 'Cabinet Pencco',
                'direction_executant' => 'INNOVATION',
                'direction_contractant' => 'INNOVATION',
                'owner_executant' => 'Bocar Sy',
                'owner_contractant' => 'Bocar Sy',
                'date_demarrage' => '2025-09-01',
                'date_fin' => '2025-12-31',
                'statut_initial' => 'En cours',
                'budget_initial' => 15000000.00,
                'objectif_projet' => 'L\'objectif principal du projet E-Teral est de moderniser et digitaliser les services en hétellerie et restauration au Sénégal en intégrant des solutions innovantes basées sur l\'intelligence artificielle et les technologies connectées. Cette transformation vise é :" Améliorer l\'expérience client gréce é des services personnalisés et adaptés aux attentes d\'une clientéle connectée." Optimiser la gestion opérationnelle des établissements en automatisant les processus clés (réservations, paiements, gestion des séjours)." Renforcer la compétitivité des acteurs locaux face aux grandes plateformes internationales (Big Tech et OTAs) en adoptant les standards du e-tourisme et des solutions intelligentes.En résumé, E-Teral ambitionne d\'accompagner les professionnels du secteur vers une transformation numérique efficace et durable, répondant aux exigences du marché moderne.',
                'prochaine_etape' => 'Recrutement des consultants Validation de la charte graphique Mise en place de l\'environment de travail',
                'ms_group_id' => '75b6ab29-6e9f-4ae7-bdfd-fbd6e75ea1fc',
                'ms_plan_id' => '45srDGNqwk2w73X52e78LWUAAnpc',
                'ms_bucket_id' => 'fw3zr85IHUOH5y_h6FAMfGUAHApO',
                'sf_opportunity_id' => null,
                'sf_opportunity_name' => null,
                'sf_opportunity_stage' => null,
                'sf_opportunity_amount' => null,
                'created_at' => '2025-09-26 16:36:43',
                'updated_at' => '2025-09-26 16:36:43',
            ],
            [
                'id' => 46,
                'user_id' => 27,
                'code_projet' => 'DPSI-GUT-0046',
                'nom_projet' => 'Réhabiltation des locaux techniques de la Douane',
                'type_projet' => 'Externe',
                'nature_projet' => 'GOV',
                'axe_strategique' => 'Stratégie',
                'filiale_executant' => 'Groupe Univers Télécom',
                'filiale_contractant' => 'Groupe Univers Télécom',
                'direction_executant' => 'PSI',
                'direction_contractant' => 'PSI',
                'owner_executant' => 'NDEYE AWA SYLLA',
                'owner_contractant' => 'NDEYE AWA SYLLA',
                'date_demarrage' => '2025-01-06',
                'date_fin' => '2025-02-28',
                'statut_initial' => 'En cours',
                'budget_initial' => 400997801.00,
                'objectif_projet' => 'Le but de ce projet est d\'apporter une réponse satisfaisante é la demande de la Direction des Douanes consistant é réhabiliter leurs locaux techniques au Bloc des Madeleines',
                'prochaine_etape' => 'Rencontre de suivi le 18 Septembre avec le client Projet avancé é 90%',
                'ms_group_id' => '03edb45d-7892-4f87-8055-1c93e5356981',
                'ms_plan_id' => 'SjnnJqKdk0OxjFiCnGQMBWUAF3js',
                'ms_bucket_id' => 'OUT0nQMEBkivwt0niitTxWUAJb-v',
                'sf_opportunity_id' => '006Vk000004iIa1IAE',
                'sf_opportunity_name' => 'TDR REHABILITATION DES LOCAUX TECHNIQUES DE LA DOUANE BDM',
                'sf_opportunity_stage' => 'Closed Won',
                'sf_opportunity_amount' => 400997801.00,
                'created_at' => '2025-10-03 13:14:01',
                'updated_at' => '2025-10-03 13:14:01',
            ],
            [
                'id' => 48,
                'user_id' => 27,
                'code_projet' => 'DPSI-GUT-0048',
                'nom_projet' => 'PROJET INTERCONNEXION DES SITES DE LA DOUANE ZONE CENTRE BUREAU ET BRIGADE DE KEUR AYIB',
                'type_projet' => 'Externe',
                'nature_projet' => 'GOV',
                'axe_strategique' => 'Stratégie',
                'filiale_executant' => 'Groupe Univers Télécom',
                'filiale_contractant' => 'Groupe Univers Télécom',
                'direction_executant' => 'PSI',
                'direction_contractant' => 'PSI',
                'owner_executant' => 'NDEYE AWA SYLLA',
                'owner_contractant' => 'NDEYE AWA SYLLA',
                'date_demarrage' => '2025-08-06',
                'date_fin' => '2025-08-25',
                'statut_initial' => 'En cours',
                'budget_initial' => 55122075.00,
                'objectif_projet' => 'La Douane sénégalaise souhaite assurer l\'interconnexion de ses sites dans la zone centre du pays comme KARANG et Keur AYIB. C\'est dans ce cadre qu\'ils avaient organisé une mission de Survey avec les équipes de GUT les 10 et 11 juillet 2025. Afin de recueillir les éléments nécessaires é la mise en production de ces sites et d\'assurer une meilleure collecte des recettes douaniéres.',
                'prochaine_etape' => 'Livraison de chaises Installation de postes téléphoniques Etablir et partager le rapport de déploiement au client Vérifier et valider les bordereaux de livraison pour chacune des prestations',
                'ms_group_id' => '76ee2be3-9f55-4c51-ba1d-5989442c07be',
                'ms_plan_id' => '-qjmhdxx5k2X7vK78picrWUACnjm',
                'ms_bucket_id' => 'DfvV9RG8Q0S3oy0WYq0I6GUANIsL',
                'sf_opportunity_id' => '006Vk00000D77wXIAR',
                'sf_opportunity_name' => 'INTERCONNEXION BUREAU ET BRIGADE DE KEUR AYIB',
                'sf_opportunity_stage' => 'Closed Won',
                'sf_opportunity_amount' => 55122076.00,
                'created_at' => '2025-10-07 11:38:48',
                'updated_at' => '2025-10-07 11:38:48',
            ],
            [
                'id' => 49,
                'user_id' => 27,
                'code_projet' => 'DPSI-GUT-0049',
                'nom_projet' => 'PROJET INTERCONNEXION DES SITES DE LA DOUANE ZONE CENTRE BUREAU ET BRIGADE DE KEUR AYIB',
                'type_projet' => 'Externe',
                'nature_projet' => 'GOV',
                'axe_strategique' => 'Stratégie',
                'filiale_executant' => 'Groupe Univers Télécom',
                'filiale_contractant' => 'Groupe Univers Télécom',
                'direction_executant' => 'PSI',
                'direction_contractant' => 'PSI',
                'owner_executant' => 'NDEYE AWA SYLLA',
                'owner_contractant' => 'NDEYE AWA SYLLA',
                'date_demarrage' => '2025-08-06',
                'date_fin' => '2025-08-25',
                'statut_initial' => 'En cours',
                'budget_initial' => 55122075.00,
                'objectif_projet' => 'La Douane sénégalaise souhaite assurer l\'interconnexion de ses sites dans la zone centre du pays comme KARANG et Keur AYIB. C\'est dans ce cadre qu\'ils avaient organisé une mission de Survey avec les équipes de GUT les 10 et 11 juillet 2025. Afin de recueillir les éléments nécessaires é la mise en production de ces sites et d\'assurer une meilleure collecte des recettes douaniéres.',
                'prochaine_etape' => 'Livraison de chaises Installation de postes téléphoniques Etablir et partager le rapport de déploiement au client Vérifier et valider les bordereaux de livraison pour chacune des prestations',
                'ms_group_id' => 'd45e992e-0a61-4faf-9e0e-bbb3c3250bf8',
                'ms_plan_id' => 'U4jfdEAhfk-zkydHdmBLHWUAC7pZ',
                'ms_bucket_id' => '3qUUHjgfHEGnWiqxG_8fc2UAHllq',
                'sf_opportunity_id' => '006Vk00000D77wXIAR',
                'sf_opportunity_name' => 'INTERCONNEXION BUREAU ET BRIGADE DE KEUR AYIB',
                'sf_opportunity_stage' => 'Closed Won',
                'sf_opportunity_amount' => 55122076.00,
                'created_at' => '2025-10-07 11:38:57',
                'updated_at' => '2025-10-07 11:38:57',
            ],
            [
                'id' => 50,
                'user_id' => 27,
                'code_projet' => 'DPSI-GUT-0050',
                'nom_projet' => 'PROJET INTERCONNEXION DES SITES DE LA DOUANE ZONE CENTRE BUREAU ET BRIGADE DE KARANG',
                'type_projet' => 'Externe',
                'nature_projet' => 'GOV',
                'axe_strategique' => 'Stratégie',
                'filiale_executant' => 'Groupe Univers Télécom',
                'filiale_contractant' => 'Groupe Univers Télécom',
                'direction_executant' => 'PSI',
                'direction_contractant' => 'PSI',
                'owner_executant' => 'NDEYE AWA SYLLA',
                'owner_contractant' => 'NDEYE AWA SYLLA',
                'date_demarrage' => '2025-10-08',
                'date_fin' => '2025-11-07',
                'statut_initial' => 'En cours',
                'budget_initial' => 48491971.00,
                'objectif_projet' => 'La Douane sénégalaise souhaite assurer l\'interconnexion de ses sites dans la zone centre du pays comme KARANG et Keur AYIB . C\'est dans ce cadre qu\'ils avaient organisé une mission de Survey avec les équipes de GUT les 10 et 11 juillet 2025. Afin de recueillir les éléments nécessaires é la mise en production de ces sites et d\'assurer une meilleure collecte des recettes douaniéres.',
                'prochaine_etape' => 'La mission est scindée en deux : les travaux passifs (cablége, etc) démarrent le Mercredi 08 Octobre. Les travaux actifs se feront dés réception du contrat signé. Partager le planning de déploiement définitif au client Démarrer la mission.',
                'ms_group_id' => '669b19c2-4593-42df-bbed-f2d9cb2f1861',
                'ms_plan_id' => 'rHD95LuczkWutsUoBVrzYmUAH4gN',
                'ms_bucket_id' => 'eqPbAltGC0CqxDZc7yUA1WUAJ07s',
                'sf_opportunity_id' => '006Vk00000D77WjIAJ',
                'sf_opportunity_name' => 'INTERCONNEXION BUREAU ET BRIGADE DOUANE DE KARANG',
                'sf_opportunity_stage' => 'Closed Won',
                'sf_opportunity_amount' => 48491971.00,
                'created_at' => '2025-10-07 11:56:19',
                'updated_at' => '2025-10-07 11:56:19',
            ],
            [
                'id' => 51,
                'user_id' => 27,
                'code_projet' => 'DPSI-GUT-0051',
                'nom_projet' => 'Support et maintenance de la plateforme SIGIF (Survey sur 50 sites)',
                'type_projet' => 'Externe',
                'nature_projet' => 'GOV',
                'axe_strategique' => 'Produits & Services',
                'filiale_executant' => 'Groupe Univers Télécom',
                'filiale_contractant' => 'Groupe Univers Télécom',
                'direction_executant' => 'PSI',
                'direction_contractant' => 'PSI',
                'owner_executant' => 'NDEYE AWA SYLLA',
                'owner_contractant' => 'NDEYE AWA SYLLA',
                'date_demarrage' => '2025-10-06',
                'date_fin' => '2025-10-25',
                'statut_initial' => 'En cours',
                'budget_initial' => 51081696.00,
                'objectif_projet' => 'L\'objectif est d\'assurer la continuité de service de la plateforme SIGIF é travers un contrat de support et de maintenance couvrant l\'ensemble de l\'infrastructure hébergée dans les datacenters principal (DTAI) et secondaire de la SENUM. Dans le but d\'assurer la disponibilité en vue du déploiement du SIGIF comptable prévu le 02/01/2026.',
                'prochaine_etape' => 'Finaliser les missions de survey Uploader les informations recueillies lors des surveys sur la plateforme Partager les rapports au client Réclamer l\'ABE',
                'ms_group_id' => 'cdf28564-e877-4f4e-a5e0-4673e643df6d',
                'ms_plan_id' => 'GJCKa-ZYpU2eKAVITpfmsmUAH50D',
                'ms_bucket_id' => 'r0Ph2Zl0wUGv1Pt8xEPTqGUAHNS5',
                'sf_opportunity_id' => '006Vk00000FXhf5IAD',
                'sf_opportunity_name' => 'SUPPORT ET MAINTENANCE DE LA PLATEFORME SIGF_SURVEY50SITES',
                'sf_opportunity_stage' => 'Soumission de l\'offre',
                'sf_opportunity_amount' => null,
                'created_at' => '2025-10-07 12:43:53',
                'updated_at' => '2025-10-07 12:43:53',
            ],
            [
                'id' => 52,
                'user_id' => 27,
                'code_projet' => 'DUTE-UTE-0052',
                'nom_projet' => 'Acquisition d\'équipements pour la remise é niveau des centrales solaires des CSFP de Bounkiling et du CFPI de Sédhiou',
                'type_projet' => 'Externe',
                'nature_projet' => 'B2B',
                'axe_strategique' => 'Commercialisation',
                'filiale_executant' => 'Univers Technology & Energies',
                'filiale_contractant' => 'Univers Technology & Energies',
                'direction_executant' => 'DIRECTION UTE',
                'direction_contractant' => 'DIRECTION UTE',
                'owner_executant' => 'Abdourahmane SOW',
                'owner_contractant' => 'Abdourahmane SOW',
                'date_demarrage' => '2025-10-13',
                'date_fin' => '2025-11-13',
                'statut_initial' => 'En cours',
                'budget_initial' => 117489000.00,
                'objectif_projet' => 'Fourniture d\'équipements pour la remise é niveau des centrales solaires des CSFP de Bounkiling et du CFPI de Sédhiou',
                'prochaine_etape' => 'Achat du matériel',
                'ms_group_id' => '5f7943d6-a691-46f7-93eb-9d36200aded7',
                'ms_plan_id' => 'R-jCTfV_4E2RxZajbyXDs2UAE6wr',
                'ms_bucket_id' => 'kR1i9z0Ki06i52FS_DkKRmUACfYj',
                'sf_opportunity_id' => '006Vk00000FJePJIA1',
                'sf_opportunity_name' => 'Acquisition d\'équipements pour la remise é niveau des centrales solaires des CSFP de Bounkiling et du CFPI de Sédhiou',
                'sf_opportunity_stage' => 'Closed Won',
                'sf_opportunity_amount' => 11748900.00,
                'created_at' => '2025-10-14 15:40:17',
                'updated_at' => '2025-10-14 15:40:17',
            ],
            [
                'id' => 53,
                'user_id' => 27,
                'code_projet' => 'DUTE-UTE-0053',
                'nom_projet' => 'Fourniture de matériels Solaire Photovoltaéque',
                'type_projet' => 'Externe',
                'nature_projet' => 'B2B',
                'axe_strategique' => 'Commercialisation',
                'filiale_executant' => 'Univers Technology & Energies',
                'filiale_contractant' => 'Univers Technology & Energies',
                'direction_executant' => 'DIRECTION UTE',
                'direction_contractant' => 'DIRECTION UTE',
                'owner_executant' => 'Abdourahmane SOW',
                'owner_contractant' => 'Abdourahmane SOW',
                'date_demarrage' => '2025-10-16',
                'date_fin' => '2025-11-13',
                'statut_initial' => 'Planifié',
                'budget_initial' => 3996200.00,
                'objectif_projet' => 'Fourniture de matériels Solaire Photovoltaéque',
                'prochaine_etape' => 'Réception du BC',
                'ms_group_id' => '52892a22-365f-4b03-8b38-e548ad1d0791',
                'ms_plan_id' => '7vk7qXfzCU6jAqBdqHc53mUADQfg',
                'ms_bucket_id' => 'qd1CKYScq0afaqIdVfQueGUABZcN',
                'sf_opportunity_id' => '006Vk00000FJXR4IAP',
                'sf_opportunity_name' => 'Fourniture de matériels Solaire Photovoltaéque',
                'sf_opportunity_stage' => 'Closed Won',
                'sf_opportunity_amount' => 3996200.00,
                'created_at' => '2025-10-14 16:33:20',
                'updated_at' => '2025-10-14 16:33:20',
            ],
            [
                'id' => 54,
                'user_id' => 27,
                'code_projet' => 'DPSI-GUT-0054',
                'nom_projet' => 'TDR Acquisition de baies de stockage sécurité',
                'type_projet' => 'Externe',
                'nature_projet' => 'GOV',
                'axe_strategique' => 'Produits & Services',
                'filiale_executant' => 'Groupe Univers Télécom',
                'filiale_contractant' => 'Groupe Univers Télécom',
                'direction_executant' => 'PSI',
                'direction_contractant' => 'PSI',
                'owner_executant' => 'NDEYE AWA SYLLA',
                'owner_contractant' => 'NDEYE AWA SYLLA',
                'date_demarrage' => '2022-10-25',
                'date_fin' => '2025-09-10',
                'statut_initial' => 'Terminé',
                'budget_initial' => 1148684113.00,
                'objectif_projet' => 'Acquisition et installation  de baie de stockage.Périmétre: - 2 baie Unity 880- 4 Switch SAN DS-6610B- 2 Switch Cisco C9300- Accessoires de connexion- Formation pour 6 agents de la Douane',
                'prochaine_etape' => 'Réception et Archivage du PV et de l\'attestation de bonne exécution.',
                'ms_group_id' => '7515740c-4563-425b-9266-e12d274293ec',
                'ms_plan_id' => 'fyoqtZc2fE-krAWij6_t9WUAAfj-',
                'ms_bucket_id' => 'Sdkz-3WzpEuyV-53XiuL7GUADusy',
                'sf_opportunity_id' => '0067Q000002BFHZQA4',
                'sf_opportunity_name' => 'ACQUISION DE BAIES STOCKAGE',
                'sf_opportunity_stage' => 'Closed Won',
                'sf_opportunity_amount' => 973461106.00,
                'created_at' => '2025-10-15 13:31:50',
                'updated_at' => '2025-10-15 13:31:50',
            ],
        ];

        // Insert in batches of 5 for performance
        foreach (array_chunk($projects, 5) as $batch) {
            DB::table('projects')->insert($batch);
        }

        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

    }
}
