<?php

namespace App\Services;

use App\Enums\ProjectType;
use App\Models\Employee;
use App\Models\Project;
use App\Services\External\MicrosoftGraphService;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class ProjectService
{
    protected $graphService;

    public function __construct(MicrosoftGraphService $graphService)
    {
        $this->graphService = $graphService;
    }

    /**
     * Create a project with all its relations.
     *
     * @param array $data Project data
     * @param array $relations Relations data (actions, deliverables, stakeholders, issues)
     * @return Project
     * @throws \Exception
     */
    public function createProject(array $data, array $relations = []): Project
    {
        DB::beginTransaction();

        try {
            // Normalize budget
            $data['budget_initial'] = $this->normalizeBudget($data['budget_initial'] ?? null);

            // Normalize Salesforce amount
            if (isset($data['sf_opportunity_amount'])) {
                $data['sf_opportunity_amount'] = $this->normalizeBudget($data['sf_opportunity_amount']);
            }

            // Normalize encaissement and decaissement
            if (isset($data['montant_encaissement'])) {
                $data['montant_encaissement'] = $this->normalizeBudget($data['montant_encaissement']);
            }
            if (isset($data['montant_decaissement_2'])) {
                $data['montant_decaissement_2'] = $this->normalizeBudget($data['montant_decaissement_2']);
            }

            // If not external, clear Salesforce data
            if (($data['type_projet'] ?? '') !== ProjectType::EXTERNE->value) {
                $data['sf_opportunity_id'] = null;
                $data['sf_opportunity_name'] = null;
                $data['sf_opportunity_stage'] = null;
                $data['sf_opportunity_amount'] = null;
            }

            // Create project (code_projet will be auto-generated by Observer)
            $project = Project::create($data);

            // Create relations
            $this->createRelations($project, $relations);

            DB::commit();

            return $project;

        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Project creation failed: ' . $e->getMessage());
            throw $e;
        }
    }

    /**
     * Update a project with all its relations.
     *
     * @param Project $project
     * @param array $data Project data
     * @param array $relations Relations data
     * @return Project
     * @throws \Exception
     */
    public function updateProject(Project $project, array $data, array $relations = []): Project
    {
        DB::beginTransaction();

        try {
            // Normalize budget
            if (isset($data['budget_initial'])) {
                $data['budget_initial'] = $this->normalizeBudget($data['budget_initial']);
            }

            if (isset($data['sf_opportunity_amount'])) {
                $data['sf_opportunity_amount'] = $this->normalizeBudget($data['sf_opportunity_amount']);
            }

            if (isset($data['montant_encaissement'])) {
                $data['montant_encaissement'] = $this->normalizeBudget($data['montant_encaissement']);
            }
            if (isset($data['montant_decaissement_2'])) {
                $data['montant_decaissement_2'] = $this->normalizeBudget($data['montant_decaissement_2']);
            }


            // Update project
            $project->update($data);

            // Update relations if provided
            if (!empty($relations)) {
                $this->updateRelations($project, $relations);
            }

            DB::commit();

            return $project->fresh();

        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Project update failed: ' . $e->getMessage());
            throw $e;
        }
    }

    /**
     * Create project relations.
     *
     * @param Project $project
     * @param array $relations
     * @return void
     */
    protected function createRelations(Project $project, array $relations): void
    {
        // Actions
        if (!empty($relations['actions'])) {
            foreach ($relations['actions'] as $index => $libelle) {
                if (!empty($libelle)) {
                    $project->actions()->create([
                        'libelle' => $libelle,
                        'ordre' => $index + 1,
                    ]);
                }
            }
        }

        // Deliverables
        if (!empty($relations['deliverables'])) {
            foreach ($relations['deliverables'] as $data) {
                if (!empty($data['livrable'])) {
                    $project->deliverables()->create([
                        'livrable' => $data['livrable'],
                        'description' => $data['description'] ?? null,
                        'date_prevue' => $data['date_prevue'] ?? null,
                        'date_reelle' => $data['date_reelle'] ?? null,
                        'statut' => $data['statut'] ?? null,
                    ]);
                }
            }
        }

        // Stakeholders (with snapshots)
        if (!empty($relations['stakeholders'])) {
            foreach ($relations['stakeholders'] as $data) {
                if (!empty($data['employe_id'])) {
                    $employee = Employee::find($data['employe_id']);

                    $project->stakeholders()->create([
                        'employe_id' => $data['employe_id'],
                        'role' => $data['role'] ?? null,
                        'snapshot_nom' => $employee?->prenom_nom,
                        'snapshot_filiale' => $employee?->filiale,
                        'snapshot_direction' => $employee?->direction,
                    ]);
                }
            }
        }

        // Issues (enjeux, contraintes, risques)
        $this->createIssues($project, $relations);
    }

    /**
     * Update project relations.
     *
     * @param Project $project
     * @param array $relations
     * @return void
     */
    protected function updateRelations(Project $project, array $relations): void
    {
        // Update actions
        if (isset($relations['actions'])) {
            // Delete existing and recreate
            $project->actions()->delete();

            foreach ($relations['actions'] as $index => $libelle) {
                if (!empty($libelle)) {
                    $project->actions()->create([
                        'libelle' => $libelle,
                        'ordre' => $index + 1,
                    ]);
                }
            }
        }

        // Update deliverables
        if (isset($relations['deliverables'])) {
            $project->deliverables()->delete();

            foreach ($relations['deliverables'] as $data) {
                if (!empty($data['livrable'])) {
                    $project->deliverables()->create([
                        'livrable' => $data['livrable'],
                        'description' => $data['description'] ?? null,
                        'date_prevue' => $data['date_prevue'] ?? null,
                        'date_reelle' => $data['date_reelle'] ?? null,
                        'statut' => $data['statut'] ?? null,
                    ]);
                }
            }
        }

        // Update stakeholders
        if (isset($relations['stakeholders'])) {
            $project->stakeholders()->delete();

            foreach ($relations['stakeholders'] as $data) {
                if (!empty($data['employe_id'])) {
                    $employee = Employee::find($data['employe_id']);

                    $project->stakeholders()->create([
                        'employe_id' => $data['employe_id'],
                        'role' => $data['role'] ?? null,
                        'snapshot_nom' => $employee?->prenom_nom,
                        'snapshot_filiale' => $employee?->filiale,
                        'snapshot_direction' => $employee?->direction,
                    ]);
                }
            }
        }

        // Update issues
        if (isset($relations['enjeux']) || isset($relations['contraintes']) || isset($relations['risques'])) {
            $project->issues()->delete();
            $this->createIssues($project, $relations);
        }
    }

    /**
     * Create project issues (enjeux, contraintes, risques).
     *
     * @param Project $project
     * @param array $relations
     * @return void
     */
    protected function createIssues(Project $project, array $relations): void
    {
        $issueTypes = [
            'enjeux' => 'Enjeux',
            'contraintes' => 'Contraintes',
            'risques' => 'Risques',
        ];

        foreach ($issueTypes as $key => $type) {
            if (!empty($relations[$key])) {
                foreach ($relations[$key] as $description) {
                    if (!empty($description)) {
                        $project->issues()->create([
                            'type_issue' => $type,
                            'description' => $description,
                            'date_identification' => now(),
                        ]);
                    }
                }
            }
        }
    }

    /**
     * Sync project to Microsoft Planner.
     *
     * @param Project $project
     * @param string|null $groupId Optional M365 Group ID
     * @return array Result with success status
     */
    public function syncToPlanner(Project $project, ?string $groupId = null): array
    {
        try {
            $result = $this->graphService->syncProjectToPlanner($project, $groupId);

            if ($result['success']) {
                Log::info("Project {$project->id} synced to MS Planner", [
                    'plan_id' => $result['plan_id'],
                    'tasks_created' => $result['tasks_created'],
                ]);
            }

            return $result;

        } catch (\Exception $e) {
            Log::error("Failed to sync project {$project->id} to Planner: " . $e->getMessage());

            return [
                'success' => false,
                'error' => $e->getMessage(),
            ];
        }
    }

    /**
     * Normalize budget (handles French comma format).
     *
     * @param mixed $value
     * @return string|null
     */
    protected function normalizeBudget($value): ?string
    {
        if (is_null($value) || $value === '') {
            return null;
        }

        // Remove spaces and replace comma with dot
        $tmp = str_replace([' ', ','], ['', '.'], (string) $value);

        if (is_numeric($tmp) && (float) $tmp >= 0) {
            return number_format((float) $tmp, 2, '.', '');
        }

        return null;
    }

    /**
     * Delete project (soft delete).
     *
     * @param Project $project
     * @return bool
     */
    public function deleteProject(Project $project): bool
    {
        try {
            return $project->delete();
        } catch (\Exception $e) {
            Log::error("Failed to delete project {$project->id}: " . $e->getMessage());
            throw $e;
        }
    }

    /**
     * Restore soft-deleted project.
     *
     * @param Project $project
     * @return bool
     */
    public function restoreProject(Project $project): bool
    {
        try {
            return $project->restore();
        } catch (\Exception $e) {
            Log::error("Failed to restore project {$project->id}: " . $e->getMessage());
            throw $e;
        }
    }

    /**
     * Force delete project (permanent).
     *
     * @param Project $project
     * @return bool
     */
    public function forceDeleteProject(Project $project): bool
    {
        try {
            return $project->forceDelete();
        } catch (\Exception $e) {
            Log::error("Failed to force delete project {$project->id}: " . $e->getMessage());
            throw $e;
        }
    }
}
